global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules and alerting
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Daily Logger Assist application
  - job_name: 'daily-logger-assist'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL database metrics (if postgres_exporter is used)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s

  # Node metrics (if node_exporter is used)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 30s

  # Nginx metrics (if nginx_prometheus_exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    scrape_interval: 30s

  # Celery metrics (if celery_exporter is used)
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_exporter:9540']
    scrape_interval: 30s

  # Docker container metrics (if cadvisor is used)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB 